### ISSUE TITLE
Heading Storybook: second variant selection triggers return to default variant

### ISSUE THREAD

**Issue by drewgingerich** [ithaka/pharos#403] opened 2022-09-02 19:29 UTC
**Expected behavior**
Selecting a variant in the Heading Storybook changes the heading variant to the selected variant.

**Actual behavior**
Selecting a variant in the Heading Storybook a second time reverts the selected variant to the default.

**Steps to reproduce the issue**

1. Visit the [Heading Button Story](https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-heading--base)
2. Navigate to the *Controls* panel
3. Select a different variant
4. Select a third variant

**Screenshots or code**

https://user-images.githubusercontent.com/15133892/188223606-275bda6e-89fa-41b0-8be9-09b9902dfbab.mov

**Comment by daneah** [comment] 2022-09-02 19:32
This is a duplicate of #402 given the broadening of its scope.

**Closed by daneah** 2022-09-02 19:32 UTC
Labels: bug, storybook, component/heading
